name: "Check Rust Project"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-project:
    name: Check Rust Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"
          cache-on-failure: true

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-dev libxkbcommon-x11-dev libx11-dev libvulkan-dev vulkan-validationlayers \
          libgtk-3-dev libgdk3.0-cil-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev \
          libwebkit2gtk-4.1-dev

      - name: Run `cargo check`
        run: cargo check

      - name: Run `cargo clippy`
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run `cargo test`
        run: cargo test --all-features
